### ISSUE TITLE
Metacard query settings do not match JSON RPC parameter names

### ISSUE THREAD

**Issue by pklinef** [connexta/revelio#223]
Query settings in the metacard schema do not all match the JSON RPC parameter names.  These parameters are currently ignored.  Paging has been fixed but sort policy and others have not been.

https://github.com/connexta/revelio/blob/master/src/main/webapp/intrigue-api/metacards/metacards.js#L28-L54

https://github.com/connexta/ddf-jsonrpc/blob/master/src/main/java/com/connexta/ddf/catalog/direct/CatalogMethods.java#L105-L111

**Comment by gjvera** [comment]
Will add the fix for this with my current pr to address some inconsistencies. https://github.com/connexta/revelio/pull/178
