### ISSUE TITLE
Default source is `ddf.distribution` when it should be the sitename

### ISSUE THREAD

**Issue by bdeining** [connexta/revelio#251]
https://github.com/connexta/revelio/blob/3979bb13e2446eac24422a0ad7b1d887d1947cd8/src/main/webapp/basic-search.js#L77
![Screen Shot 2020-02-25 at 4 00 53 PM](https://user-images.githubusercontent.com/6551038/75295591-3b787280-57e8-11ea-8b6b-1533abfe15d5.png)
https://github.com/connexta/revelio/blob/59c3d743a0b65ac299a9003150424358cfef2909/src/main/webapp/search-forms/editor.tsx#L91

**Comment by willwill96** [comment]
Default Source should be `All Sources` according to intrigue
