### ISSUE TITLE
When duplicating an index card the modified state persists from the original metacard...

### ISSUE THREAD

**Issue by gjvera** [connexta/revelio#282]
The modified time should be the created time of the new metacard

**Comment by willwill96** [comment]
This could also be an issue for the [JSON RPC repo](https://github.com/connexta/ddf-jsonrpc)

**Comment by gjvera** [comment]
@willwill96 I think it's something on our end because it looks like those attributes are cleared out on the RPC side.
https://github.com/connexta/ddf-jsonrpc/blob/master/src/main/java/com/connexta/ddf/catalog/direct/ExtendedMethods.java#L130

**Comment by willwill96** [comment]
I think we should probably add `Core.METACARD_MODIFIED` and `Core.METACARD_CREATED` to that list.

**Comment by willwill96** [comment]
Fixed by: https://github.com/connexta/ddf-jsonrpc/pull/15
