### ISSUE TITLE
Adding Match Types to basic searh freezes the page

### ISSUE THREAD

**Issue by AzGoalie** [connexta/revelio#312]
When creating a basic search and adding the 'Match Types' option, the page will freeze and then turn blank. In the console it reports the following errors.

```
react-beautiful-dnd

An error has occurred while a drag is occurring.
Any existing drag will be cancelled.

> TypeError: immutable_1.getIn(...) is null
```

**Comment by samuelechu** [comment]
did you get an additional error `Cannot read property '__reactstandin__key' of undefined`?
